name: 更新大乐透数据和分析报告

on:
  schedule:
    # 每天晚上23:00 (UTC+8) 运行，对应 15:00 UTC
    - cron: '0 15 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]  # 推送到main分支时触发
  pull_request:
    branches: [ main ]  # PR合并到main分支时触发
    types: [ closed ]   # 只在PR关闭时触发

jobs:
  update-super-lotto-data:
    runs-on: ubuntu-latest
    # 确保PR只在合并时运行，而不是简单关闭时运行
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 缓存pip依赖
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy matplotlib seaborn beautifulsoup4
        
    - name: 运行大乐透数据分析
      run: |
        python super_lotto_analyzer.py
        
    - name: 检查文件变更
      id: git-check
      run: |
        git diff --exit-code super_lotto_data.json super_lotto_analysis_report.md || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: 提交更新
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add super_lotto_data.json
        git add super_lotto_analysis_report.md
        git add super_lotto_frequency_analysis.png
        git commit -m "🎯 更新大乐透数据 - $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') (UTC+8)"
        git push
        
    - name: 创建重大更新的发布版本
      if: steps.git-check.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取当前日期作为tag (使用UTC+8时区)
        TAG_NAME="super-lotto-$(TZ='Asia/Shanghai' date +'%Y%m%d')"
        
        # 检查tag是否已存在
        if ! git tag | grep -q "^$TAG_NAME$"; then
          # 创建tag和release
          git tag $TAG_NAME
          git push origin $TAG_NAME
          
          # 创建release notes
          cat > release_notes.md << EOF
        ## 🎯 大乐透数据更新 - $(TZ='Asia/Shanghai' date +'%Y年%m月%d日') (UTC+8)
        
        ### 📊 本次更新内容
        - 抓取最新大乐透开奖数据
        - 更新统计分析图表
        - 刷新号码频率分析
        - 更新分析报告文档
        
        ### 📁 更新文件
        - \`super_lotto_data.json\` - 最新开奖数据
        - \`super_lotto_analysis_report.md\` - 详细分析报告
        - \`super_lotto_frequency_analysis.png\` - 频率分析图表
        
        ### ⚠️ 免责声明
        本数据仅供学习和统计分析使用，彩票开奖完全随机，请理性购彩。
        EOF
          
          # 使用GitHub CLI创建release
          gh release create $TAG_NAME \
            --title "大乐透数据更新 $TAG_NAME" \
            --notes-file release_notes.md \
            super_lotto_data.json \
            super_lotto_analysis_report.md \
            super_lotto_frequency_analysis.png
        fi
        
    - name: 输出结果
      run: |
        if [ "${{ steps.git-check.outputs.changed }}" == "true" ]; then
          echo "✅ 大乐透数据已更新并提交 - $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') (UTC+8)"
        else
          echo "ℹ️ 大乐透数据无变化，跳过提交 - $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S') (UTC+8)"
        fi 